//
//  InstallmentSelectionRouter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol InstallmentSelectionRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol InstallmentSelectionDataPassing {
    var dataStore: InstallmentSelectionDataStore? { get }
}

class InstallmentSelectionRouter: NSObject, InstallmentSelectionRoutingLogic, InstallmentSelectionDataPassing {
    weak var viewController: InstallmentSelectionViewController?
    var dataStore: InstallmentSelectionDataStore?

    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: InstallmentSelectionViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: InstallmentSelectionDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
