//
//  InstallmentSelectionInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentSelectionBusinessLogic {
    func getInstallments()
}

protocol InstallmentSelectionDataStore {
    var installmentsResponse: InstallmentsResponse! { get set }
}

class InstallmentSelectionInteractor: InstallmentSelectionBusinessLogic, InstallmentSelectionDataStore {
    var presenter: InstallmentSelectionPresentationLogic?
    var worker: InstallmentSelectionWorker?

    var installmentsResponse: InstallmentsResponse!

    func getInstallments() {
        let response = InstallmentSelection.Installment.Response(installmentsResponse: installmentsResponse)
        presenter?.presentView(response: response)
    }
}
