//
//  InstallmentSelectionPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentSelectionPresentationLogic {
    func presentView(response: InstallmentSelection.Installment.Response)
}

class InstallmentSelectionPresenter: InstallmentSelectionPresentationLogic {
    weak var viewController: InstallmentSelectionDisplayLogic?

    func presentView(response: InstallmentSelection.Installment.Response) {
        var displayedInstallmentArray = [InstallmentSelection.Installment.ViewModel.DisplayedInstallment]()

        let payerCosts = response.installmentsResponse[0]

        for installment in payerCosts.payerCosts {
            let displayedInstallment = InstallmentSelection.Installment.ViewModel.DisplayedInstallment(recommendedMessage: installment.recommendedMessage, installments: String(installment.installments), installmentValue: "$\(installment.installmentAmount)", totalAmount: "$\(installment.totalAmount)")
            displayedInstallmentArray.append(displayedInstallment)
        }
        let viewModel = InstallmentSelection.Installment.ViewModel(displayedInstallments: displayedInstallmentArray)
        viewController?.displayView(viewModel: viewModel)
    }
}
