//
//  InstallmentSelectionInteractor.swift
//  MercadoPagoExample
//
//  Created by Orlando Arzola on 1/27/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentSelectionBusinessLogic {
    func getInstallments()
    func getToSummary(request: InstallmentSelection.Summary.Request)
}

protocol InstallmentSelectionDataStore {
    var installmentsResponse: InstallmentsResponse! { get set }
    var paymentFlowBuilder: PaymentFlowDataBuilder! { get set }
}

class InstallmentSelectionInteractor: InstallmentSelectionBusinessLogic, InstallmentSelectionDataStore {
    var presenter: InstallmentSelectionPresentationLogic?
    var worker: InstallmentSelectionWorker?

    var installmentsResponse: InstallmentsResponse!
    var paymentFlowBuilder: PaymentFlowDataBuilder!

    func getInstallments() {
        let response = InstallmentSelection.Installment.Response(installmentsResponse: installmentsResponse)
        presenter?.presentView(response: response)
    }

    func getToSummary(request: InstallmentSelection.Summary.Request) {
        let installment = installmentsResponse[0].payerCosts[request.index]
        _ = paymentFlowBuilder.withSelectedInstallment(installment: installment)
        presenter?.presentSummary()
    }
}
