//
//  InstallmentSelectionInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentSelectionBusinessLogic {
    func doSomething(request: InstallmentSelection.Something.Request)
}

protocol InstallmentSelectionDataStore {
    //var name: String { get set }
}

class InstallmentSelectionInteractor: InstallmentSelectionBusinessLogic, InstallmentSelectionDataStore {
    var presenter: InstallmentSelectionPresentationLogic?
    var worker: InstallmentSelectionWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: InstallmentSelection.Something.Request) {
        worker = InstallmentSelectionWorker()
        worker?.doSomeWork()

        let response = InstallmentSelection.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
