//
//  InstallmentSelectionPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentSelectionPresentationLogic {
    func presentSomething(response: InstallmentSelection.Something.Response)
}

class InstallmentSelectionPresenter: InstallmentSelectionPresentationLogic {
    weak var viewController: InstallmentSelectionDisplayLogic?

    // MARK: Do something

    func presentSomething(response: InstallmentSelection.Something.Response) {
        let viewModel = InstallmentSelection.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
