//
//  PaymentSelectionWorkerTests.swift
//  MercadoPagoExample
//
//  Created by Orlando Arzola on 1/29/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MPEDebug
import XCTest

class PaymentSelectionWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: PaymentSelectionWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupPaymentSelectionWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupPaymentSelectionWorker() {
        sut = PaymentSelectionWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
