//
//  BankSelectionPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BankSelectionPresentationLogic {
    func presentView(response: BankSelection.BankIssuers.Response)
    func presentInstallments()
    func presentLoading()
    func dismissLoading()
    func presentError()
}

class BankSelectionPresenter: BankSelectionPresentationLogic {
    weak var viewController: BankSelectionDisplayLogic?

    func presentView(response: BankSelection.BankIssuers.Response) {
        var bankIssuersArray = [BankSelection.BankIssuers.ViewModel.DisplayedBankIssuers]()

        for issuer in response.bankIssuersResponse {
            let bankIssuer = BankSelection.BankIssuers.ViewModel.DisplayedBankIssuers(name: issuer.name, imageURL: issuer.secureThumbnail)
            bankIssuersArray.append(bankIssuer)
        }
        let viewModel = BankSelection.BankIssuers.ViewModel(diplayedBankIssuersArray: bankIssuersArray)

        viewController?.displayView(viewModel: viewModel)
    }

    func presentInstallments() {
        viewController?.displayInstallments()
    }

    func presentLoading() {
        viewController?.dismissLoading()
    }

    func dismissLoading() {
        viewController?.dismissLoading()
    }

    func presentError() {
        let viewModel = BankSelection.Error.ViewModel(title: "", message: "")
        viewController?.displayError(viewModel: viewModel)
    }
}
