//
//  BankSelectionModels.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BankSelection {
    // MARK: Use cases

    enum BankIssuers {
        struct Response {
            var bankIssuersResponse: BanksResponse
        }

        struct ViewModel {
            struct DisplayedBankIssuers: OptionViewModel {
                var name: String
                var imageURL: String
            }

            var diplayedBankIssuersArray: [DisplayedBankIssuers]
        }
    }

    enum Error {
        struct ViewModel {
            var title: String
            var message: String
        }
    }

    enum Installment {
        struct Request {
            var index: Int
        }
    }
}
