//
//  PaymentSelectionPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentSelectionPresentationLogic {
    func presentLoading()
    func dismissLoading()
    func presentView(response: PaymentSelection.PaymentMethods.Response)
    func presentBankIssuers()
    func presentError()
}

class PaymentSelectionPresenter: PaymentSelectionPresentationLogic {
    weak var viewController: PaymentSelectionDisplayLogic?


    func presentLoading() {
        viewController?.displayLoading()
    }

    func dismissLoading() {
        viewController?.dismissLoading()
    }

    func presentView(response: PaymentSelection.PaymentMethods.Response) {
        var displayedPaymentMethods = [PaymentSelection.PaymentMethods.ViewModel.DisplayedPaymentMethods]()
        for method in response.paymentMethods {
            let displayedMethod = PaymentSelection.PaymentMethods.ViewModel.DisplayedPaymentMethods(name: method.name, imageURL: method.secureThumbnail)
            displayedPaymentMethods.append(displayedMethod)
        }
        let viewModel = PaymentSelection.PaymentMethods.ViewModel(displayedPaymentMethodsArray: displayedPaymentMethods)
        viewController?.displayView(viewModel: viewModel)
    }

    func presentBankIssuers() {
        viewController?.displayBankIssuers()
    }

    func presentError() {
        let viewModel = PaymentSelection.Error.ViewModel(title: "Opps", message: "Something went wrong")
        viewController?.displayError(viewModel: viewModel)
    }

}
