//
//  PaymentSelectionRouter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PaymentSelectionRoutingLogic {
    func routeToBankIssuers()
}

protocol PaymentSelectionDataPassing {
    var dataStore: PaymentSelectionDataStore? { get }
}

class PaymentSelectionRouter: NSObject, PaymentSelectionRoutingLogic, PaymentSelectionDataPassing {
    weak var viewController: PaymentSelectionViewController?
    var dataStore: PaymentSelectionDataStore?

    // MARK: Routing

    func routeToBankIssuers() {
        let destinationVC = BankSelectionViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToBankSelection(source: dataStore!, destination: &destinationDS)
        navigateToBankSelection(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToBankSelection(source: PaymentSelectionViewController, destination: BankSelectionViewController)
    {
      source.navigationController?.pushViewController(destination, animated: true)
    }

    // MARK: Passing data

    func passDataToBankSelection(source: PaymentSelectionDataStore, destination: inout BankSelectionDataStore)
    {
      destination.bankIssuers = source.bankIssuers
    }
}
