//
//  SummaryRouter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SummaryRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToStart()
}

protocol SummaryDataPassing {
    var dataStore: SummaryDataStore? { get }
}

class SummaryRouter: NSObject, SummaryRoutingLogic, SummaryDataPassing {
    weak var viewController: SummaryViewController?
    var dataStore: SummaryDataStore?

    // MARK: Routing

    func routeToStart() {
        viewController?.navigationController?.popToRootViewController(animated: true)
    }
}
