//
//  SummaryInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryBusinessLogic {
    func doSomething(request: Summary.Something.Request)
}

protocol SummaryDataStore {
    //var name: String { get set }
}

class SummaryInteractor: SummaryBusinessLogic, SummaryDataStore {
    var presenter: SummaryPresentationLogic?
    var worker: SummaryWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: Summary.Something.Request) {
        worker = SummaryWorker()
        worker?.doSomeWork()

        let response = Summary.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
