//
//  SummaryInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryBusinessLogic {
    func getSummary()
}

protocol SummaryDataStore {
    var amount: String! { get set }
    var totalAmount: String! { get set }
    var paymentMethod: String! { get set }
    var issuer: String! { get set }
    var installments: String! { get set }
    var installmentValue: String! { get set }
}

class SummaryInteractor: SummaryBusinessLogic, SummaryDataStore {
    var presenter: SummaryPresentationLogic?
    var worker: SummaryWorker?

    var installments: String!
    var installmentValue: String!
    var amount: String!
    var totalAmount: String!
    var paymentMethod: String!
    var issuer: String!


    func getSummary() {
        let response = Summary.Summary.Response(installments: installments, installmentValue: installmentValue, amount: amount, totalAmount: totalAmount, paymentMethod: paymentMethod, issuer: issuer)
        presenter?.presentSummary(response: response)
    }
}
