//
//  SummaryInteractor.swift
//  MercadoPagoExample
//
//  Created by Orlando Arzola on 1/27/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryBusinessLogic {
    func getSummary()
}

protocol SummaryDataStore {
    var paymentFlowBuilder: PaymentFlowDataBuilder! { get set }
}

class SummaryInteractor: SummaryBusinessLogic, SummaryDataStore {
    var presenter: SummaryPresentationLogic?
    var worker: SummaryWorker?

    var paymentFlowBuilder: PaymentFlowDataBuilder!

    func getSummary() {
        let paymentData = paymentFlowBuilder.build()
        let response = Summary.Summary.Response(installments: String(paymentData.selectedInstallment.installments), installmentValue: String(paymentData.selectedInstallment.installmentAmount), amount: paymentData.amount, totalAmount: String(paymentData.selectedInstallment.totalAmount), paymentMethod: paymentData.selectedPaymentMethod.name, issuer: paymentData.selectedIssuer.name)
        presenter?.presentSummary(response: response)
    }
}
