//
//  SummaryPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryPresentationLogic {
    func presentSomething(response: Summary.Something.Response)
}

class SummaryPresenter: SummaryPresentationLogic {
    weak var viewController: SummaryDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Summary.Something.Response) {
        let viewModel = Summary.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
