//
//  AmountInputInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountInputBusinessLogic {
    func doSomething(request: AmountInput.Something.Request)
}

protocol AmountInputDataStore {
    //var name: String { get set }
}

class AmountInputInteractor: AmountInputBusinessLogic, AmountInputDataStore {
    var presenter: AmountInputPresentationLogic?
    var worker: AmountInputWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: AmountInput.Something.Request) {
        worker = AmountInputWorker()
        worker?.doSomeWork()

        let response = AmountInput.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
