//
//  AmountInputPresenter.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountInputPresentationLogic {
    func presentSomething(response: AmountInput.Something.Response)
}

class AmountInputPresenter: AmountInputPresentationLogic {
    weak var viewController: AmountInputDisplayLogic?

    // MARK: Do something

    func presentSomething(response: AmountInput.Something.Response) {
        let viewModel = AmountInput.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
