//
//  AmountInputRouter.swift
//  MercadoPagoExample
//
//  Created by Orlando Arzola on 1/27/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AmountInputRoutingLogic {
    func routeToPaymentSelection()
}

protocol AmountInputDataPassing {
    var dataStore: AmountInputDataStore? { get }
}

class AmountInputRouter: NSObject, AmountInputRoutingLogic, AmountInputDataPassing {
    weak var viewController: AmountInputViewController?
    var dataStore: AmountInputDataStore?

    // MARK: Routing

    func routeToPaymentSelection() {
        let destinationVC = PaymentSelectionViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToPaymentSelection(source: dataStore!, destination: &destinationDS)
        navigateToPaymentSelection(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToPaymentSelection(source: AmountInputViewController, destination: PaymentSelectionViewController)
    {
      source.navigationController?.pushViewController(destination, animated: true)
    }

//     MARK: Passing data

    func passDataToPaymentSelection(source: AmountInputDataStore, destination: inout PaymentSelectionDataStore)
    {
        destination.paymentFlowBuilder = source.paymentFlowBuilder
    }
}
