//
//  AmountInputInteractor.swift
//  MercadoPagoExample
//
//  Created by Orlando Arzola on 1/27/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountInputBusinessLogic {
    func textFieldDidChange(text: String)
}

protocol AmountInputDataStore {
    var paymentFlowBuilder: PaymentFlowDataBuilder! { get set }
}

class AmountInputInteractor: AmountInputBusinessLogic, AmountInputDataStore {
    var presenter: AmountInputPresentationLogic?
    var worker: AmountInputWorker?

    var paymentFlowBuilder: PaymentFlowDataBuilder! = PaymentFlowDataBuilder()

    func textFieldDidChange(text: String) {
        if let amount = Int(text), amount > 10 {
            _ = self.paymentFlowBuilder.withAmount(amount: text)
            presenter?.presentEnabledContinueButton()
        } else {
            presenter?.presentDisabledContinueButton()
        }
    }

}
