//
//  AmountInputInteractor.swift
//  MercadoPagoExample
//
//  Created by Nisum on 1/27/19.
//  Copyright (c) 2019 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountInputBusinessLogic {
    func textFieldDidChange(text: String)
}

protocol AmountInputDataStore {
    var amount: String! { get set }
}

class AmountInputInteractor: AmountInputBusinessLogic, AmountInputDataStore {
    var presenter: AmountInputPresentationLogic?
    var worker: AmountInputWorker?

    var amount: String!

    func textFieldDidChange(text: String) {
        if let amount = Int(text), amount > 10 {
            self.amount = String(amount)
            presenter?.presentEnabledContinueButton()
        } else {
            presenter?.presentDisabledContinueButton()
        }
    }

}
